name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */8 * * *'  
  workflow_dispatch: 
  #workflow_dispatch helps run workflow anytime with a single click.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        # NOTE: this pins the action to a specific commit sha for security
        # reasons but you can also use a version tag if desired. For example:
        # ianwalter/playwright-container@v1.1.1
        uses: ianwalter/playwright-container@ec253ce35910412cc6607f5d7cfbbe89fb77c9b4
        with:
          args: npm ci
      - name: Test
        uses: ianwalter/playwright-container@ec253ce35910412cc6607f5d7cfbbe89fb77c9b4
        with:
          args: npm run save
      # - name: Deploy Dexes
      #   uses: exuanbo/actions-deploy-gist@v1
      #   with:
      #     token: ${{ secrets.GIST_TOKEN }}
      #     gist_id: f48cf25668db546bbcb66aeb3f1ead91
      #     gist_file_name: dex-pools.json
      #     file_path: ./dex-pools.json
      - name: Deploy Dexes
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'dex-pools.json'
          destination_repo: 'kitchenswap/kitchenswap-data'
          user_email: 'hanna.waffle@gmail.com'
          user_name: 'hannawaffle'
      # - name: Get Logos
      #     run: npm run logos
      # - name: Deploy Images
      #   uses: exuanbo/actions-deploy-gist@v1
      #   with:
      #     token: ${{ secrets.GIST_TOKEN }}
      #     gist_id: f48cf25668db546bbcb66aeb3f1ead91
      #     gist_file_name: token-logos.json
      #     file_path: ./token-logos.json