name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */8 * * *'  
  workflow_dispatch: 
  #workflow_dispatch helps run workflow anytime with a single click.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
        run: npm install
        run: npm run save
      - name: Deploy Dexes
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'dex-pools.json'
          destination_repo: 'kitchenswap/kitchenswap-data'
          user_email: 'hanna.waffle@gmail.com'
          user_name: 'hannawaffle'
      - name: Update Dex Urls
        run: npm run dex-urls
      - name: Deploy New Dex Urls
        if: hashFiles('dex-urls.json') != ''
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'dex-urls.json'
          destination_repo: 'kitchenswap/kitchenswap-data'
          user_email: 'hanna.waffle@gmail.com'
          user_name: 'hannawaffle'
      - name: Get Logos
        run: npm run token-logos
      - name: Deploy New logos
        if: hashFiles('token-logos.json') != ''
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'token-logos.json'
          destination_repo: 'kitchenswap/kitchenswap-data'
          user_email: 'hanna.waffle@gmail.com'
          user_name: 'hannawaffle'
      # - name: Get Contracts
      #   run: npm run token-contracts
      # - name: Deploy New Contracts
      #   if: hashFiles('token-contracts.json') != ''
      #   uses: dmnemec/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source_file: 'token-contracts.json'
      #     destination_repo: 'kitchenswap/kitchenswap-data'
      #     user_email: 'hanna.waffle@gmail.com'
      #     user_name: 'hannawaffle'
      - name: Deploy pancakebunny
        if: hashFiles('pancakebunny.json') != ''
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'pancakebunny.json'
          destination_repo: 'kitchenswap/kitchenswap-data'
          user_email: 'hanna.waffle@gmail.com'
          user_name: 'hannawaffle'
